### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by matsaleh13** [gajus/prettyprint#3]
This looks useful and I would like to try it out, but I can't find a license. What license are you using, if any? If not, please choose one. It will make your package more accessible to users who are sensitive to such things.

Thanks, and nice work.

**Comment by gajus** [comment]
Addressed in https://github.com/gajus/prettyprint/tree/v1.1.1 (BSD-3-Clause).

**Comment by matsaleh13** [comment]
Excellent, thanks! Great package btw!
