### ISSUE TITLE
Breaks on yarn because of node ^5 requirement

### ISSUE THREAD

**Issue by vjpr** [gajus/prettyprint#4]
Update version requirement.

**Comment by gajus** [comment]
Can you provide more information? I haven't used Yarn yet. I am assuming it strictly enforces the engine requirements?

**Comment by vjpr** [comment]
```
"engines": {
  "node": "^5.0.0"
},
```

Yarn will throw an error if your current version doesn't match (unless you use `yarn install --ignore-engines`).

**Comment by gajus** [comment]
Addressed in https://github.com/gajus/prettyprint/tree/v1.1.1 (Made it +5.0.0).
