### ISSUE TITLE
Wrong path to modules

### ISSUE THREAD

**Issue by Taskkill** [gajus/prettyprint#5]
Cannot find module '/Users/gajus/Documents/dev/gajus/pragmatist/node_modules/source-map-support/register.js'

After installation.

**Comment by gajus** [comment]
Have you tried inspecting where the path is hardcoded? Looks like some sort of compilation error.

**Comment by Taskkill** [comment]
Actually no I have not.
I was just quicky trying to print something in console so I tried your package, this poped out and before I just printed it like JSON I decided to inform you.

**Comment by mssalnikov** [comment]
+1 same issue here

to reproduce:

`npm i -D pretty-print-object`
`echo "require('pretty-print-object')" > index.js`
`node index.js`
